use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `KafkaClient` resource, directly
/// reflects context of the `kafkaclients.example.com.yaml` file to be found in this repository.
/// The `KafkaClient` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "example.com",
    version = "v1",
    kind = "KafkaClient",
    plural = "kafkaclients",
    derive = "PartialEq",
    namespaced
)]
pub struct KafkaClientSpec {
    pub replicas: i32,
}
